#!/bin/bash
#PBS -N GP12001024_0.1_2
#PBS -l nodes=1:ppn=64
#PBS -l mem=300gb
#PBS -q debug
#PBS -j oe
#PBS -o ./run.log



cd $PBS_O_WORKDIR
date > ./run.log
export FC='ifort'
export XFLAG_NO_OMP='-O3 -fpp -q -coarray=distributed -mcmodel=large -coarray-config-file=cafconfig.txt'
export XFLAG='-O3 -fpp -qopenmp -coarray=distributed -mcmodel=large -coarray-config-file=cafconfig.txt'
export OFLAG_NO_OMP=$XFLAG_NO_OMP' -c'
export OFLAG=$XFLAG' -c'
export FFTFLAG='-I/opt/intel2018update3/mkl/include/fftw -mkl'
export OMP_STACKSIZE=20000M
export OMP_NUM_THREADS=64
export FOR_COARRAY_NUM_IMAGES=1
ulimit
ulimit -s unlimited
ulimit -u unlimited 
ulimit -v unlimited 


echo ""
echo ""
echo ""
echo ""
export PROCS=1
export ntasks_per_node=1
sort $PBS_NODEFILE | uniq -c | awk -v npn=$ntasks_per_node  '{print \$2":"npn}' > ./hostfile_$PROCS 
HOST_FILE=./hostfile_$PROCS
pwd

run_program() {
    local cmd="$1"
    echo ""
    echo "++++++++++++++++++++++++++++++++++++++++++++++"
    echo "Running $cmd"
    echo "++++++++++++++++++++++++++++++++++++++++++++++"
    echo ""
    echo "-genvall -machinefile $HOST_FILE -n $PROCS $cmd"   > cafconfig.txt 
    $cmd
    echo ""
    echo "++++++++++++++++++++++++++++++++++++++++++++++"
    echo "Finish $cmd"
    echo "++++++++++++++++++++++++++++++++++++++++++++++"
    echo ""
    echo ""
}

### RUN ###
echo running with ${PBS_NP} processes on ${PBS_NUM_NODES} nodes
echo "###############################################"
echo "Start Running"
umask 002
IC=./utilities/ic.x
cic=./utilities/cic.x
MAIN=./main.x
CIC=./utilities/cicpower.x
OCIC=./utilities/ocicpower.x
FOF=./utilities/fof.x
DSP=./utilities/dsp.x
C2U=./utilities/cdm2nu.x
# run_program $IC
# run_program $cic
run_program $MAIN
run_program $CIC
# run_program $FOF
# run_program $DSP
# run_program $C2U
echo "Finish ALL"
date
