boltzmann_code     =  camb
boltzmann_folder   =  /home/cbh/anaconda3/bin/
k_per_logint_camb  =  10
outputfile         =  ../IC/IC_0.1
; output_format      =  camb transfer function
output_format      = power spectra
wrong_nu           =  0
print_hubble       =  T
z_final            =  0.
z_initial          = 200.
output_number      =  5
z_output           =  0.0 19.0 49.0 99.0 200.
h                  =  0.7
OB0                =  0.04630
OC0                =  0.23050887231422523
OG0                =  2.469e-05
Neff               =  0.00641
M_nu               =  0.1
w0                 = -1.0
wa                 =  0.0
As                 =  2.6025e-09
tau_reio           =  0.0925
ns                 =  0.972
kmax               =  100.0
N_nu               =  3.0